[package]
name = "ldap3_server"
version = "0.1.6"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"

description = "LDAP Server Codec for Tokio"
repository = "https://github.com/kanidm/ldap3_server"
readme = "README.md"
keywords = ["ldap", "authentication"]
categories = ["authentication"]
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lber = "0.3"
tokio-util = { version = "0.6", features = ["codec"] }
bytes = "1"

[dev-dependencies]
env_logger = "0.8"
log = "0.4"

futures-util = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "io-util", "net", "signal", "macros"] }
futures = "0.3"
